---
services:
  python:
    build:
      context: python/
      dockerfile: Dockerfile
      args:
        - UID
        - GID
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ../:/workspace
