[project]
name = "python-workspace"
version = "0.1.0"
description = "Development and execution environment for Python"
readme = "README.md"
requires-python = "==3.14.0"
dependencies = []

[dependency-groups]
dev = ["ruff==0.14.0"]
