target-version = "py314"
line-length = 120
exclude = []

[lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "D203", # incorrect-blank-line-before-class
    "D212", # multi-line-summary-first-line
    "D400", # missing-trailing-period
    "D415", # missing-terminal-punctuation
    "T201", # print
]
unfixable = [
    "F401", # unused-import
    "F841", # unused-variable
]
