---
name: run_github_actions_workflow_ci

on:
  push:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
